### ISSUE TITLE
Navagation bar color is not consistent when keyboard is docked

### ISSUE THREAD

**Issue by jbpratt** [MemeLabs/strims-android#47]
![one](https://i.imgur.com/ziTvjHq.png)
![two](https://i.imgur.com/mbjGRb1.png)

**Comment by kamakazechickn** [comment]
I am unable to replicate this issue since I have moved on to a different phone that no longer has a software nav bar.

**Comment by jbpratt** [comment]
@kamakazechickn thanks for the update, we will go ahead and close it. Feel free to re-open it if you run into it again.
