### ISSUE TITLE
Emote combo text is too large

### ISSUE THREAD

**Issue by kamakazechickn** [MemeLabs/strims-android#65]
https://imgur.com/a/tlgHmHZ

The combo text for emotes is large and inconsistent. Sometimes the x3  combo is larger than the x4 combo. In all cases, this text goes off the screen and uses multiple lines.

**Comment by jbpratt** [comment]
Hi @kamakazechickn , this should be fixed in the latest release. Please feel free to reopen if the bug is still present.
